apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ template "version" .}}
    chart: "{{ .Chart.Name }}"
    app: "{{ .Release.Name }}"
    heritage: {{ .Release.Service | quote }}
data:
  redis.conf: |-
    bind 0.0.0.0
    port 6379
    logfile ""
    pidfile "/data/tmp/redis.pid"
    dir "/data/redis/redis/"
    {{- if and .Values.persistence.enabled .Values.persistence.redisRDB }}
    save 900 1
    save 300 10
    save 60 1000
    appendonly no
    {{- else }}
    save ""
    appendonly yes
    {{- end }}
    maxmemory-policy volatile-lru

  slave.conf: |-
    bind 0.0.0.0
    port 6379
    logfile ""
    pidfile "/data/tmp/redis.pid"
    dir "/data/redis/redis/"
    slave-read-only yes
    {{- if and .Values.persistence.enabled .Values.persistence.redisRDB }}
    save 900 1
    save 300 10
    save 60 1000
    appendonly no
    {{- else }}
    save ""
    appendonly yes
    {{- end }}
    maxmemory-policy volatile-lru
{{- if and .Values.cluster.enabled .Values.sentinel.enabled }}
  sentinel.conf: |-
    bind 0.0.0.0
    port 26379
    sentinel monitor mymasterSet {{ .Release.Name }}-master-0.{{ .Release.Name }}-master-headless.{{ .Values.namespace }}.svc.{{ .Values.clusterDomain }} 6379 {{ .Values.sentinel.quorum }}
    sentinel down-after-milliseconds mymasterSet 5000
    sentinel failover-timeout mymasterSet 60000
    sentinel parallel-syncs mymasterSet 1
    dir "/data/redis/sentinel/"
{{- end }}
