---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master-headless
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ template "version" .}}
    chart: "{{ .Chart.Name }}"
    app: "{{ .Release.Name }}"
    heritage: {{ .Release.Service | quote }}
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  selector:
    app: "{{ .Release.Name }}"
    role: master

{{- if .Values.cluster.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-slave-headless
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ template "version" .}}
    chart: "{{ .Chart.Name }}"
    app: "{{ .Release.Name }}"
    heritage: {{ .Release.Service | quote }}
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  selector:
    app: "{{ .Release.Name }}"
    role: slave
{{- end }}
