{{- if .Values.usePassword.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ template "version" .}}
    chart: "{{ .Chart.Name }}"
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.usePassword.redisPassword }}
  redis-password: {{ .Values.usePassword.redisPassword | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
